backend:
  name: github
  repo: BoidCMS/boidcms.github.io
  branch: master
  use_graphql: true

site_url: https://boidcms.github.io
logo_url: https://boidcms.github.io/_media/logo.svg

media_folder: _media

collections:
  - name: Documentations
    label: Docs
    label_singular: Documentation
    folder: '/'
    create: true
    nested:
      depth: 5
      summary: '{{filename}}'
    identifier_field: '{{filename}}'
    fields:
      - label: Content
        name: body
        widget: markdown
